version: "3.3"
services:
  mongo:
    ports: 
      - "27017:27017"
    container_name: mongo-server
    restart: always
    logging:
      options:
        max-size: "1g"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo:latest