version: "3.3"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo-server
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPass
    volumes:
      - mongo-data:/data/db
    logging:
      options:
        max-size: "1g"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: